### ISSUE TITLE
error in line no 7

### ISSUE THREAD

**Issue by bipeensinha** [bipeensinha/letsdoit#1]
dear all,

there is an error, please have a look
@dragos-vilcescu work with @obuzea and update to @Marin-Martin

**Comment by dragos-vilcescu** [comment]
Working on it

**Comment by Deleuiuly** [comment]
I am working on it now

**Comment by obuzea** [comment]
You are wrong, everything is ok 🙂

**Comment by andreibirsan** [comment]
on it

**Comment by thstef** [comment]
I look into it

**Comment by bipeensinha** [comment]
I am working on it
![demo](https://user-images.githubusercontent.com/49720823/144833911-050bfaeb-800b-44c1-9887-1c9461e1ff9b.jpeg)
i got , pic is incorrect

**Comment by MaKedonu96** [comment]
I am working on this issue

**Comment by bipeensinha** [comment]
thanks
